#! /bin/sh

# for some reason lightdm (?) is turning on numlock when I log in
numlockx off
sxhkd &
polybar example 2>/dev/null &
feh --bg-fill ~/Pictures/outrun4k.jpg
compton 2>/dev/null &
emacs --daemon=mail
emacs --daemon
getmail --rcfile=~/.getmail/getgmailrc &
getmail --rcfile=~/.getmail/getunirc &

bspc config focus_follows_pointer true

bspc monitor -d genrl hackr email chati

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

## Start-up apps in specific workspaces
# In workspace 1 (genrl), have web-browser.



