#!/bin/bash

export HOSTNAME=$(hostname)
case $HOSTNAME in
    earth)
        monitor1=DP-4
        monitor2=DVI-D-0
        ;;
    *)
        monitor1=
        monitor2=doesntexist
        ;;
esac

bspc config focus_follows_pointer true

bspc monitor $monitor1 -d genrl hackr email chati

# TODO This only configures the root node on each monitor. If I move a
# node from one monitor to another, the node will keep the
# configuration of its previous desktop. This isn't horrific as long
# as windows are spawned on the "correct" monitor, but is ugly on the
# rare occasion that it happens.

bspc config -m $monitor1 border_width    8
bspc config -m $monitor1 window_gap      20
bspc config -m $monitor1 top_padding     50
bspc config -m $monitor1 bottom_padding  10
bspc config -m $monitor1 left_padding    40
bspc config -m $monitor1 right_padding   40

bspc config -m $monitor2 border_width    4
bspc config -m $monitor2 window_gap      20
bspc config -m $monitor2 bottom_padding  0
bspc config -m $monitor2 top_padding     0
bspc config -m $monitor2 left_padding    0
bspc config -m $monitor2 right_padding   0

bspc config active_border_color          '#FFFFFF'
bspc config focused_border_color         '#b576da'
bspc config normal_border_color          '#000000'
bspc config presel_border_color          '#31aeff'
bspc config urgent_border_color          '#ff9e24'
bspc config presel_feedback_color        '#ec9946'

bspc config split_ratio          0.5     
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp       desktop='^8' state=floating follow=on
bspc rule -a Chromium   desktop='^2'
bspc rule -a mplayer2   state=floating
bspc rule -a Kupfer.py  focus=on
bspc rule -a Screenkey  manage=off
bspc rule -a Emacs      state=tiled
bspc rule -a MATLAB     state=floating

# for some reason lightdm (?) is turning on numlock when I log in
numlockx off
sxhkd &
polybar example 2>/home/mgsk/polybaroutput &
feh --bg-fill ~/Pictures/BladeRunner1.jpg
offlineimap &
compton 2>/dev/null &
redshift &
# Emacs daemon for email.
emacs -q --eval '(setq server-name "mail")' --load ~/hackery/emacs.g/init.el --daemon
# Emacs daemon for everything else
emacs -q --load ~/hackery/emacs.g/init.el --daemon
#getmail --rcfile=~/.getmail/getgmailrc &
#getmail --rcfile=~/.getmail/getunirc &
caffeine &

bspwm_single_node $monitor1 &

