#!/bin/sh

export HOSTNAME=$(hostname)
case $HOSTNAME in
    earth)
        monitor1=DP-4
        monitor2=DVI-D-0
        bw1=8
        wg1=20
        tp1=50
        bp1=10
        lp1=40
        rp1=40
        bw2=4
        wg2=20
        tp2=0
        bp2=0
        lp2=0
        rp2=0
        ;;
    *)
        monitor1=HDMI-0
        monitor2=
        bw1=4
        wg1=15
        tp1=50
        bp1=10
        lp1=15
        rp1=15
        bw2=0
        wg2=0
        tp2=0
        bp2=0
        lp2=0
        rp2=0
        ;;
esac

bspc monitor $monitor1 -d genrl hackr email chati readi

# TODO This only configures the root node on each monitor. If I move a
# node from one monitor to another, the node will keep the
# configuration of its previous desktop. This isn't horrific as long
# as windows are spawned on the "correct" monitor, but is ugly on the
# rare occasion that it happens.

bspc config -m $monitor1 border_width    $bw1
bspc config -m $monitor1 window_gap      $wg1
bspc config -m $monitor1 top_padding     $tp1
bspc config -m $monitor1 bottom_padding  $bp1
bspc config -m $monitor1 left_padding    $lp1
bspc config -m $monitor1 right_padding   $rp1

if [ ! -z $monitor2 ]; then
    bspc config -m $monitor2 border_width    $bw2
    bspc config -m $monitor2 window_gap      $wg2
    bspc config -m $monitor2 bottom_padding  $tp2
    bspc config -m $monitor2 top_padding     $bp2
    bspc config -m $monitor2 left_padding    $lp2
    bspc config -m $monitor2 right_padding   $rp2
fi

bspc config active_border_color          '#FFFFFF'
bspc config focused_border_color         '#b576da'
bspc config normal_border_color          '#000000'
bspc config presel_feedback_color        '#ec9946'

bspc config split_ratio          0.5     
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp       desktop='^8' state=floating follow=on
bspc rule -a Chromium   desktop='^2'
bspc rule -a mplayer2   state=floating
bspc rule -a Kupfer.py  focus=on
bspc rule -a Screenkey  manage=off
bspc rule -a Emacs      state=tiled
bspc rule -a MATLAB     state=floating

# NOTE All tools, including bspc, should be installed by
# configuration.nix / whatever prior to running this. No checks are
# made for unavailable executables, and so this startup script will
# fail if any are missing.
feh --bg-fill ~/Pictures/backgrounds/current-background.jpg

pgrep -f polybar >/dev/null || polybar example 2>/home/mgsk/polybaroutput &
pgrep -f sxhkd >/dev/null || sxhkd &
pgrep -f compton >/dev/null || compton 2>/dev/null &
pgrep -f redshift >/dev/null || redshift &
pgrep -f blueman-applet >/dev/null || blueman-applet &
pgrep -f pasystray >/dev/null || pasystray &

# TODO Override (and increase) the left/right padding configuration
# for a desktop with a single window. Prevents a single window
# spanning the full width of a large monitor (bad for readability).
#
# TODO Fix this.
#pgrep -f bspwm_single_node >/dev/null || ./bspwm_single_node HDMI-0 &

